[project]
name = 'clarunit test contracts'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

# Test comment in order to have changes
# Add changes
# Add major keyword
# Add minor keyword
# Bump each commit
# Run the workflow again
# Set bump each commit to true
# Set searching in body for releases to true - for merges