name: Publish Packages

on: push

jobs:
  print_version:
    name: Print the semver of clarunit package
    runs-on: ubuntu-latest
    steps:
      - name: Call composite
        id: print_semver
        uses: BowTiedDevOps/actions/publish-packages@feat/test-tools-npm-publish
        with: # Use the defaults for testing purposes - modify later
          major_pattern: "MAJOR"
          minor_pattern: "MINOR"
          version_format: "${major}.${minor}.${increment}"
          change_path: "packages/clarunit"
          bump_each_commit: "false"
          bump_each_commit_patch_pattern: ""
          search_commit_body: "true"
          debug: "true"
